version: '3'

services:

  db:
    build:
      dockerfile: ./docker/image/Dockerfile
      context: "../"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678

    container_name: hospital_db

    ports:
      - "5432:5432"

    networks:
      - hospital

networks:
  hospital:
    driver: bridge